name: myhashicorprepo_dev_workflow1
on:
  push:
    branches:
      - main
jobs:
  get-secret:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    name: get-secret
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v3.3.0
        with:
          url: https://vault-cluster-public-vault-a9973be8.e25832b5.z1.hashicorp.cloud:8200
          path: jwt-dev-actions
          role: auth.jwt.dev_role
          method : jwt
          exportToken: true
          exportEnv: true
          namespace: admin
          secrets: |
            MyDevSecrets/data/repo:myhashicorprepo_dev/workflow:myhashicorprepo_dev_workflow1 secretkey | APPSECRET ;
      - name: Step following 'Import Secrets'
        run: |
          echo '${{ toJson(steps.import-secrets.outputs) }}' > secrets.json
          cat ./secrets.json
          #echo 'For bash'
          APPSECRET="${{ env.APPSECRET }}"
          echo "Stored Output: $APPSECRET"
          #echo 'for windows'         
          #$APPSECRET = "${{ env.APPSECRET }}"
          #echo "Stored Output: $APPSECRET"
